<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerURYjHVu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerURYjHVu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerURYjHVu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerURYjHVu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerURYjHVu\App_KernelDevDebugContainer([
    'container.build_hash' => 'URYjHVu',
    'container.build_id' => 'b8f751c9',
    'container.build_time' => 1765972342,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerURYjHVu');
