<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'user_list' => [[], ['_controller' => 'App\\Controller\\UserController::list'], [], [['text', '/users']], [], [], []],
    'user_add' => [[], ['_controller' => 'App\\Controller\\UserController::add'], [], [['text', '/users/add']], [], [], []],
    'user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], [], []],
];
